<a href="https://colab.research.google.com/github/CHERUKURISUHARSHITHA/FML_LAB/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a=np.array([1,2,3])
print(a.shape)

(3,)


In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
b=a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[6,7,8,9]])
print(a[0,1])
b=np.array([[2,4,6,8],[1,3,5,7]])
print(b[0,0])

2
2


In [ ]:
import numpy as np
a=np.array([[4,6],[7,11]])
print(a)
row_1=a[1,:]
row_2=a[1:0,:]
col_1=a[:,1]
col_2=a[:,1:0]
print(row_1,row_1.shape)
print(row_2,row_2.shape)
print(col_1,col_1.shape)
print(col_2,col_2.shape)


[[ 4  6]
 [ 7 11]]
[ 7 11] (2,)
[] (0, 2)
[ 6 11] (2,)
[] (2, 0)


In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[6,7,8,9]])
b=np.array([[1,4,3,4],[4,6,7,11]])


[[1. 0.]
 [0. 1.]]


In [ ]:
import numpy as np
a=([[1,2,3,4],[5,6,7,8]])
b=([[2,4,7,5],[8,4,1,9]])
print(a+b)
print(np.add(a,b))


[[1, 2, 3, 4], [5, 6, 7, 8], [2, 4, 7, 5], [8, 4, 1, 9]]
[[ 3  6 10  9]
 [13 10  8 17]]


In [ ]:
e=np.random.random((11,7))
print(e)

[[0.0329454  0.9669909  0.27887012 0.86106839 0.46472591 0.74205933
  0.14869822]
 [0.93674475 0.73573397 0.4164404  0.87350922 0.82892999 0.09351251
  0.07954355]
 [0.73450494 0.90793193 0.42831597 0.45757871 0.15641602 0.23175827
  0.06125469]
 [0.44654724 0.11843416 0.71318387 0.23575497 0.61112025 0.01905608
  0.62964858]
 [0.64962247 0.70100059 0.34775807 0.96643148 0.90971055 0.530834
  0.26825277]
 [0.4997564  0.087357   0.03228323 0.87613098 0.91625444 0.77246913
  0.80822291]
 [0.82098851 0.21295223 0.78682313 0.15763209 0.01523793 0.57467108
  0.60836052]
 [0.89332775 0.39276379 0.38014153 0.54404455 0.90854788 0.1215364
  0.04577671]
 [0.6526883  0.29328397 0.1738122  0.85600698 0.78702037 0.76825155
  0.98346405]
 [0.47047792 0.84214804 0.93780571 0.48541343 0.00249336 0.220802
  0.24519851]
 [0.39793241 0.18525378 0.21296166 0.89696284 0.24265479 0.88047919
  0.91615407]]


In [ ]:
z=np.eye(2)
print(z)


[[1. 0.]
 [0. 1.]]


In [ ]:
import numpy as np
